dataset:
  path_to_data: data/casl_3305_runs_inter.h5
  fraction_of_data: 0.1

  inputs:
    power_W_g: MinMax
    U238: MinMax
  targets:
    U238: MinMax

  target_delta_conc: False
  train:
    batch_size: 512
  val:
    batch_size: 8192
    
model:
  name: NODE_mae_test_big
  layers: [128, 128]
  dropout_probability: 0.0
  activation: tanh
  output_activation: none
  residual_connections: false

train:
  loss: mae
  learning_rate: 5e-5
  weight_decay: 0.0
  lr_scheduler_patience: 10
  num_epochs: 20000
  early_stopping_patience: 50
  grad_clip: 1.0
  drop_last: false

runtime:
  mode: train
  model: NODE
  ckp_path: results/NODE_Test/best-NODE_Test-epoch=195.ckpt
  device: cuda
  seed: 42
  num_workers: 6
  model_database: Chain_Model.db