name: nuclear-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openmc
  - pytorch
  - lightning
  - torchdiffeq
  - numpy
  - pandas
  - matplotlib
  - h5py
  - optuna
  - polars 
  - scikit-learn
  - seaborn
  - omegaconf
  - loguru
  - tdqm
  - pytest         
  - pip
  - pip:
    - -e .